import {createColumnHelper} from "@tanstack/react-table";

export interface Order {
    id: number
    date: string
    total: number
    status: 'Pending' | 'Shipped' | 'Delivered' | 'Cancelled'
    customer: { name: string, email: string }
    paymentMethod: string
    isDelivered: boolean
}

const columnHelper = createColumnHelper<Order>()

export const tableColumns = [
    columnHelper.group({
        id: 'order',
        header: () => <div className='border-b border-r p-4'>Order</div>,
        columns: [
            columnHelper.accessor('id', {cell: props => <div className='min-w-20'>{props.getValue()}</div>}),
            columnHelper.accessor('date', {header: 'Date'}),
            columnHelper.accessor('total', {header: 'Total'}),
            columnHelper.accessor('status', {header: 'Status'}),
            columnHelper.accessor('isDelivered', {header: 'Delivered', cell: info => info.getValue() ? 'Yes' : 'No'}),
        ]
    }),
    columnHelper.group({
        id: 'client',
        header: () => <div className='border-b p-4'>Client</div>,
        columns: [
            columnHelper.accessor(row => `${row.customer.name} ${row.customer.email}`, {
                id: 'customer',
                header: 'Customer'
            }),
        ]
    }),
    columnHelper.accessor('paymentMethod', {
        header: () => <div className='border-l p-4'>Payment Method</div>,
    }),
]

export const mockOrders: Order[] = [
    {
        id: 1001,
        date: '2023-10-15T08:30:00Z',
        status: 'Pending',
        total: 50.00,
        customer: {name: 'Alice Johnson', email: 'alice@example.com'},
        paymentMethod: 'Credit Card',
        isDelivered: false,
    },
    {
        id: 1002,
        date: '2023-10-14T06:30:00Z',
        status: 'Shipped',
        total: 63.75,
        customer: {name: 'Bob Smith', email: 'bob@example.com'},
        paymentMethod: 'PayPal',
        isDelivered: true,
    },
    {
        id: 1003,
        date: '2023-10-13T04:30:00Z',
        status: 'Delivered',
        total: 77.50,
        customer: {name: 'Charlie Brown', email: 'charlie@example.com'},
        paymentMethod: 'Cash',
        isDelivered: true,
    },
    {
        id: 1004,
        date: '2023-10-12T02:30:00Z',
        status: 'Cancelled',
        total: 91.25,
        customer: {name: 'Diana Prince', email: 'diana@example.com'},
        paymentMethod: 'Debit Card',
        isDelivered: false,
    },
    {
        id: 1005,
        date: '2023-10-11T00:30:00Z',
        status: 'Pending',
        total: 105.00,
        customer: {name: 'Ethan Hunt', email: 'ethan@example.com'},
        paymentMethod: 'Bank Transfer',
        isDelivered: false,
    },
    {
        id: 1006,
        date: '2023-10-09T22:30:00Z',
        status: 'Shipped',
        total: 118.75,
        customer: {name: 'Fiona Gallagher', email: 'fiona@example.com'},
        paymentMethod: 'Credit Card',
        isDelivered: true,
    },
    {
        id: 1007,
        date: '2023-10-08T20:30:00Z',
        status: 'Delivered',
        total: 132.50,
        customer: {name: 'George Miller', email: 'george@example.com'},
        paymentMethod: 'PayPal',
        isDelivered: true,
    },
    {
        id: 1008,
        date: '2023-10-07T18:30:00Z',
        status: 'Cancelled',
        total: 146.25,
        customer: {name: 'Hannah Baker', email: 'hannah@example.com'},
        paymentMethod: 'Cash',
        isDelivered: false,
    },
    {
        id: 1009,
        date: '2023-10-06T16:30:00Z',
        status: 'Pending',
        total: 160.00,
        customer: {name: 'Ian Wright', email: 'ian@example.com'},
        paymentMethod: 'Debit Card',
        isDelivered: false,
    },
    {
        id: 1010,
        date: '2023-10-05T14:30:00Z',
        status: 'Shipped',
        total: 173.75,
        customer: {name: 'Julia Roberts', email: 'julia@example.com'},
        paymentMethod: 'Bank Transfer',
        isDelivered: true,
    },
    {
        id: 1011,
        date: '2023-10-04T12:30:00Z',
        status: 'Delivered',
        total: 187.50,
        customer: {name: 'Kevin Hart', email: 'kevin@example.com'},
        paymentMethod: 'Credit Card',
        isDelivered: true,
    },
    {
        id: 1012,
        date: '2023-10-03T10:30:00Z',
        status: 'Cancelled',
        total: 201.25,
        customer: {name: 'Laura Palmer', email: 'laura@example.com'},
        paymentMethod: 'PayPal',
        isDelivered: false,
    },
    {
        id: 1013,
        date: '2023-10-02T08:30:00Z',
        status: 'Pending',
        total: 215.00,
        customer: {name: 'Michael Scott', email: 'michael@example.com'},
        paymentMethod: 'Cash',
        isDelivered: false,
    },
    {
        id: 1014,
        date: '2023-10-01T06:30:00Z',
        status: 'Shipped',
        total: 228.75,
        customer: {name: 'Nina Simone', email: 'nina@example.com'},
        paymentMethod: 'Debit Card',
        isDelivered: true,
    },
    {
        id: 1015,
        date: '2023-09-30T04:30:00Z',
        status: 'Delivered',
        total: 242.50,
        customer: {name: 'Oscar Wilde', email: 'oscar@example.com'},
        paymentMethod: 'Bank Transfer',
        isDelivered: true,
    },
    {
        id: 1016,
        date: '2023-09-29T02:30:00Z',
        status: 'Cancelled',
        total: 256.25,
        customer: {name: 'Paula Abdul', email: 'paula@example.com'},
        paymentMethod: 'Credit Card',
        isDelivered: false,
    },
    {
        id: 1017,
        date: '2023-09-28T00:30:00Z',
        status: 'Pending',
        total: 270.00,
        customer: {name: 'Quentin Tarantino', email: 'quentin@example.com'},
        paymentMethod: 'PayPal',
        isDelivered: false,
    },
    {
        id: 1018,
        date: '2023-09-26T22:30:00Z',
        status: 'Shipped',
        total: 283.75,
        customer: {name: 'Rachel Green', email: 'rachel@example.com'},
        paymentMethod: 'Cash',
        isDelivered: true,
    },
    {
        id: 1019,
        date: '2023-09-25T20:30:00Z',
        status: 'Delivered',
        total: 297.50,
        customer: {name: 'Steve Rogers', email: 'steve@example.com'},
        paymentMethod: 'Debit Card',
        isDelivered: true,
    },
    {
        id: 1020,
        date: '2023-09-24T18:30:00Z',
        status: 'Cancelled',
        total: 311.25,
        customer: {name: 'Tina Fey', email: 'tina@example.com'},
        paymentMethod: 'Bank Transfer',
        isDelivered: false,
    },
    {
        id: 1021,
        date: '2023-09-23T16:30:00Z',
        status: 'Pending',
        total: 325.00,
        customer: {name: 'Uma Thurman', email: 'uma@example.com'},
        paymentMethod: 'Credit Card',
        isDelivered: false,
    },
    {
        id: 1022,
        date: '2023-09-22T14:30:00Z',
        status: 'Shipped',
        total: 338.75,
        customer: {name: 'Victor Hugo', email: 'victor@example.com'},
        paymentMethod: 'PayPal',
        isDelivered: true,
    },
    {
        id: 1023,
        date: '2023-09-21T12:30:00Z',
        status: 'Delivered',
        total: 352.50,
        customer: {name: 'Wendy Darling', email: 'wendy@example.com'},
        paymentMethod: 'Cash',
        isDelivered: true,
    },
    {
        id: 1024,
        date: '2023-09-20T10:30:00Z',
        status: 'Cancelled',
        total: 366.25,
        customer: {name: 'Xander Cage', email: 'xander@example.com'},
        paymentMethod: 'Debit Card',
        isDelivered: false,
    },
    {
        id: 1025,
        date: '2023-09-19T08:30:00Z',
        status: 'Pending',
        total: 380.00,
        customer: {name: 'Yara Greyjoy', email: 'yara@example.com'},
        paymentMethod: 'Bank Transfer',
        isDelivered: false,
    },
    {
        id: 1026,
        date: '2023-09-18T06:30:00Z',
        status: 'Shipped',
        total: 393.75,
        customer: {name: 'Zach Galifianakis', email: 'zach@example.com'},
        paymentMethod: 'Credit Card',
        isDelivered: true,
    },
    {
        id: 1027,
        date: '2023-09-17T04:30:00Z',
        status: 'Delivered',
        total: 407.50,
        customer: {name: 'Amanda Waller', email: 'amanda@example.com'},
        paymentMethod: 'PayPal',
        isDelivered: true,
    },
    {
        id: 1028,
        date: '2023-09-16T02:30:00Z',
        status: 'Cancelled',
        total: 421.25,
        customer: {name: 'Bruce Wayne', email: 'bruce@example.com'},
        paymentMethod: 'Cash',
        isDelivered: false,
    },
    {
        id: 1029,
        date: '2023-09-15T00:30:00Z',
        status: 'Pending',
        total: 435.00,
        customer: {name: 'Clark Kent', email: 'clark@example.com'},
        paymentMethod: 'Debit Card',
        isDelivered: false,
    },
    {
        id: 1030,
        date: '2023-09-13T22:30:00Z',
        status: 'Shipped',
        total: 448.75,
        customer: {name: 'Diego Rivera', email: 'diego@example.com'},
        paymentMethod: 'Bank Transfer',
        isDelivered: true,
    },
    {
        id: 1031,
        date: '2023-09-12T20:30:00Z',
        status: 'Delivered',
        total: 462.50,
        customer: {name: 'Elena Gilbert', email: 'elena@example.com'},
        paymentMethod: 'Credit Card',
        isDelivered: true,
    },
    {
        id: 1032,
        date: '2023-09-11T18:30:00Z',
        status: 'Cancelled',
        total: 476.25,
        customer: {name: 'Frank Castle', email: 'frank@example.com'},
        paymentMethod: 'PayPal',
        isDelivered: false,
    },
    {
        id: 1033,
        date: '2023-09-10T16:30:00Z',
        status: 'Pending',
        total: 490.00,
        customer: {name: 'Grace Kelly', email: 'grace@example.com'},
        paymentMethod: 'Cash',
        isDelivered: false,
    },
    {
        id: 1034,
        date: '2023-09-09T14:30:00Z',
        status: 'Shipped',
        total: 53.75,
        customer: {name: 'Henry Ford', email: 'henry@example.com'},
        paymentMethod: 'Debit Card',
        isDelivered: true,
    },
    {
        id: 1035,
        date: '2023-09-08T12:30:00Z',
        status: 'Delivered',
        total: 67.50,
        customer: {name: 'Isabella Swan', email: 'isabella@example.com'},
        paymentMethod: 'Bank Transfer',
        isDelivered: true,
    },
    {
        id: 1036,
        date: '2023-09-07T10:30:00Z',
        status: 'Cancelled',
        total: 81.25,
        customer: {name: 'Jack Sparrow', email: 'jack@example.com'},
        paymentMethod: 'Credit Card',
        isDelivered: false,
    },
    {
        id: 1037,
        date: '2023-09-06T08:30:00Z',
        status: 'Pending',
        total: 95.00,
        customer: {name: 'Karen Page', email: 'karen@example.com'},
        paymentMethod: 'PayPal',
        isDelivered: false,
    },
    {
        id: 1038,
        date: '2023-09-05T06:30:00Z',
        status: 'Shipped',
        total: 108.75,
        customer: {name: 'Leo Fitz', email: 'leo@example.com'},
        paymentMethod: 'Cash',
        isDelivered: true,
    },
    {
        id: 1039,
        date: '2023-09-04T04:30:00Z',
        status: 'Delivered',
        total: 122.50,
        customer: {name: 'Monica Geller', email: 'monica@example.com'},
        paymentMethod: 'Debit Card',
        isDelivered: true,
    },
    {
        id: 1040,
        date: '2023-09-03T02:30:00Z',
        status: 'Cancelled',
        total: 136.25,
        customer: {name: 'Natasha Romanoff', email: 'natasha@example.com'},
        paymentMethod: 'Bank Transfer',
        isDelivered: false,
    },
];

